window.google||(google={});if(!window.google.update)google.update={};google.update.d=[];function _GU_OnloadHandlerAdd(c,b){var a=google.update.d.length;if(typeof b=="number")if(b<a&&b>=0)a=b;google.update.d.splice(a,0,c)}function _GU_OnloadBody(c){var b=window.google.update.d;if(b)for(var a=0;a<b.length;++a)b[a](c)}
function _GU_getPlatform(){if(window.google.update.e)return window.google.update.e;return window.google.update.e=navigator.platform=="Win32"?"win":navigator.platform=="WinCE"?"wince":/linux/i.test(navigator.platform)?"linux":/mac/i.test(navigator.platform)?"mac":"win"}
function _GU_getBrowserId(){if(window.google.update.a)return window.google.update.a;window.google.update.a=0;if(navigator.userAgent.indexOf("Opera")!=-1)window.google.update.a=0;else if(navigator.userAgent.indexOf("Firefox")!=-1)window.google.update.a=3;else if(navigator.userAgent.indexOf("MSIE")!=-1)if(navigator.userAgent.indexOf("Windows CE")!=-1)window.google.update.a=0;else{if(navigator.userAgent.indexOf("PPC")==-1&&navigator.userAgent.indexOf("Smartphone")==-1)window.google.update.a=2}else if(navigator.userAgent.indexOf("Chrome")!=
-1)window.google.update.a=4;else if(navigator.userAgent.indexOf("Safari")!=-1)window.google.update.a=0;return window.google.update.a}function _GU_setCookie(c,b,a){var d=c+"="+escape(b);if(-1!=a){var e=new Date;e.setMinutes(e.getMinutes()+a);d+=";expires="+e.toUTCString()}document.cookie=d}function _GU_setSessionCookie(c,b){_GU_setCookie(c,b,-1)}
function _GU_getCookie(c){if(document.cookie){var b=document.cookie.indexOf(c+"=");if(b!=-1&&(b==0||document.cookie.substring(b-2,b-1)==";")){b=b+c.length+1;var a=document.cookie.indexOf(";",b);if(a==-1)a=document.cookie.length;return unescape(document.cookie.substring(b,a))}}return""}function _GU_removeCookie(c){_GU_setCookie(c,"",0)}function _GU_areCookiesSupported(){_GU_setCookie("test","1",1);var c=_GU_getCookie("test")=="1";_GU_removeCookie("test");return c}
function _GU_initIid(){function c(){function a(){for(var d=65536,e=Math.floor(Math.random()*d),g=e.toString(16);g.length<4;)g="0"+g;return g.toUpperCase()}return"{"+a()+a()+"-"+a()+"-"+a()+"-"+a()+"-"+a()+a()+a()+"}"}var b=_GU_getCookie("iid");if(b)window.google.update.b=b;else if(_GU_areCookiesSupported()){window.google.update.b=c();_GU_setSessionCookie("iid",window.google.update.b)}else window.google.update.b="{11112222-3333-4444-5555-666677778888}"}
function _GU_getIid(){window.google.update.b||_GU_initIid();return window.google.update.b}function _GU_createAppInfo(c,b,a,d){var e={};e.c=c;e.name=b;e.g=a;e.f=d;return e}
function GU_BuildTag(c,b){b||(b="");for(var a="",d=0;d<c.length;++d){if(d==0){a+="appguid="+c[d].c;a+=b}else a+="&appguid="+c[d].c;a+="&appname="+encodeURIComponent(c[d].name).replace(/~/g,"%7E").replace(/\!/g,"%21").replace(/\*/g,"%2A").replace(/\(/g,"%28").replace(/\)/g,"%29").replace(/\'/g,"%27");a+="&needsadmin="+c[d].g;if(c[d].f)a+=c[d].f}return a}function GU_buildGlobalExtra(c,b){var a="&iid="+_GU_getIid()+"&lang="+c+"&browser="+_GU_getBrowserId()+"&usagestats=";a+=b?"1":"0";return a}
function _GU_isClickOnceAvailable(){function c(b){function a(j,l){var i=0,k=0,m=0;do{k=i<j.length?Number(j[i]):0;m=i<l.length?Number(l[i]):0;++i}while((i<j.length||i<l.length)&&k==m);if(k<m)return-1;if(k>m)return 1;return 0}var d=navigator.userAgent.match(/\.NET CLR [0-9.]+/g);if(d==null||d.length==0)return false;var e=b.split(".");if(e.length==0)return false;for(var g=0;g<d.length;++g){var f=d[g].match(/\.NET CLR ([0-9.]+)/);if(!(f==null||f.length!=2)){var h=f[1].split(".");if(h.length>0&&a(e,h)<=
0)return true}}return false}if(2!=_GU_getBrowserId())return false;return c("2.0.0")}function _GU_isOneClickAvailable(){return window.google.update&&window.google.update.oneclick}function _GU_SetupOneClick(){_GU_SetupOneClickVersions(["8"])}
function _GU_SetupOneClickVersions(c){function b(f){var h=document.createElement("object");h.width="0";h.height="0";h.vspace="0";h.type="application/x-vnd.google.oneclickctrl."+f;h.id="OneClickCtrl";document.body.appendChild(h);return h}if(!(window.google.update&&window.google.update.oneclick))if(!("win"!=_GU_getPlatform())){for(var a=0;a<c.length;++a){var d=c[a];try{new ActiveXObject("Google.OneClickCtrl."+d);window.google.update.oneclickPlugin_=b(d)}catch(e){var g=navigator.mimeTypes["application/x-vnd.google.oneclickctrl."+d];if(g&&
g.enabledPlugin)window.google.update.oneclickPlugin_=b(d)}if(window.google.update.oneclickPlugin_)break}if(!(!window.google.update.oneclickPlugin_||window.location.search.indexOf("nooneclick")>=0))if(!window.google.update.oneclick)window.google.update.oneclick={getOneClickVersion:function(){try{return window.google.update.oneclickPlugin_.GetOneClickVersion()}catch(f){return-1}},install:function(f,h,j,l,i){var k="http://tools.google.com";k+="/service/update2/installping";var m=GU_buildGlobalExtra(h,
j),q='"'+GU_BuildTag(f,m)+'"';for(a=0;a<f.length;++a){var o=k;o+="?appid="+encodeURIComponent(f[a].c);o+="&lang="+encodeURIComponent(h);o+="&iid="+encodeURIComponent(_GU_getIid());o+="&installsource=oneclick";var r=new Image;r.src=o}var s="/install "+q;try{window.google.update.oneclickPlugin_.Install(s,l,i)}catch(p){var n=p.number;n||(n=parseInt(p,"0x"==p.substring(0,1)?16:10));if(isNaN(n)||0==n)n=-2;i(n)}},getInstalledVersion:function(f,h){var j="";try{j=window.google.update.oneclickPlugin_.GetInstalledVersion(f,
h)}catch(l){}return j}}}}function _GU_buildDlPath(c,b,a,d,e){var g=GU_buildGlobalExtra(b,a),f=GU_BuildTag(c,g);return d+"/tag/s/"+encodeURIComponent(f)+e}function _GU_buildDlPathNoTag(c,b,a,d,e){return d+"/"+e}function _GU_buildClickOncePath(c,b,a,d,e){var g=GU_buildGlobalExtra(b,a),f=GU_BuildTag(c,g);return d+e+"?"+encodeURIComponent(f)};
